services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '127.0.0.1:${REDIS_PORT}:${REDIS_PORT}'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-secret}
    command: >
      sh -c "redis-server
      --requirepass $$REDIS_PASSWORD"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/dockerfile
    container_name: gateway
    depends_on:
      - redis
      - journal
      - data-pipeline
    env_file:
      - .env
    ports:
      - '4050:4050'
    restart: unless-stopped

  journal:
    build:
      context: .
      dockerfile: apps/journal/dockerfile
    container_name: journal
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - '4051:4051'
    restart: unless-stopped

  data-pipeline:
    build:
      context: .
      dockerfile: apps/data-pipeline/dockerfile
    container_name: data-pipeline
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - '4052:4052'
    restart: unless-stopped

volumes:
  redis-data: